// Code generated by "goenums"; DO NOT EDIT.

package main

import (
	"database/sql/driver"
	"fmt"
)

type OperationStatus string

const (
	OperationStatusPending   OperationStatus = "Pending"
	OperationStatusOnGoing   OperationStatus = "OnGoing"
	OperationStatusCompleted OperationStatus = "Completed"
	OperationStatusPostponed OperationStatus = "Postponed"
	OperationStatusCancelled OperationStatus = "Cancelled"
)

func (e OperationStatus) IsValid() bool {
	validValues := []string{
		"Pending",
		"OnGoing",
		"Completed",
		"Postponed",
		"Cancelled",
	}

	for _, val := range validValues {
		if val == string(e) {
			return true
		}
	}
	return false
}

func (e OperationStatus) ValidValues() []string {
	return []string{
		"Pending",
		"OnGoing",
		"Completed",
		"Postponed",
		"Cancelled",
	}
}

func (e *OperationStatus) Scan(src interface{}) error {
	source, ok := src.(string)
	if !ok {
		return fmt.Errorf("invalid value for %s: %s", "OperationStatus", source)
	}
	*e = OperationStatus(source)
	return nil
}

func (e OperationStatus) Value() (driver.Value, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("invalid value for %s", "OperationStatus")
	}
	return string(e), nil
}
